"""users_locations_refactor

Revision ID: d63338fa5256
Revises: dbfb91ec7147
Create Date: 2026-07-01 19:52:09.623627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63338fa5256'
down_revision: Union[str, Sequence[str], None] = 'dbfb91ec7147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_locations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'location_id')
    )
    # WAŻNE: zamiast op.drop_table używamy op.rename_table — dane nie są tracone!
    # Po ręcznej migracji danych (INSERT INTO users SELECT ... FROM users_old)
    # możesz usunąć stare tabele: op.drop_table('users_old') i op.drop_table('locations_old')
    op.drop_index('ix_service_points_id', table_name='service_points')
    op.rename_table('service_points', 'locations_old')   # <-- RENAME zamiast DROP
    op.drop_index('ix_admins_username', table_name='admins')
    op.rename_table('admins', 'users_old')               # <-- RENAME zamiast DROP
    op.add_column('tablets', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('tablets', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))  # server_default potrzebne dla NOT NULL na istniejących wierszach
    op.add_column('tablets', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tablets', sa.Column('pairing_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'tablets', ['location_id'])
    op.drop_constraint('tablets_service_point_id_fkey', 'tablets', type_='foreignkey')
    op.create_foreign_key(None, 'tablets', 'locations', ['location_id'], ['id'])
    op.drop_column('tablets', 'location')
    op.drop_column('tablets', 'service_point_id')
    op.add_column('tickets', sa.Column('called_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('served_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('customer_name', sa.String(length=120), nullable=True))
    op.add_column('tickets', sa.Column('appointment_time', sa.String(length=20), nullable=True))
    op.add_column('tickets', sa.Column('served_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('tickets', sa.Column('location_id', sa.Integer(), nullable=False))
    op.drop_constraint('tickets_service_point_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['served_by_user_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'locations', ['location_id'], ['id'])
    op.drop_column('tickets', 'service_point_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('service_point_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_service_point_id_fkey', 'tickets', 'service_points', ['service_point_id'], ['id'])
    op.drop_column('tickets', 'location_id')
    op.drop_column('tickets', 'served_by_user_id')
    op.drop_column('tickets', 'appointment_time')
    op.drop_column('tickets', 'customer_name')
    op.drop_column('tickets', 'served_at')
    op.drop_column('tickets', 'called_at')
    op.add_column('tablets', sa.Column('service_point_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tablets', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tablets', type_='foreignkey')
    op.create_foreign_key('tablets_service_point_id_fkey', 'tablets', 'service_points', ['service_point_id'], ['id'])
    op.drop_constraint(None, 'tablets', type_='unique')
    op.drop_column('tablets', 'pairing_token')
    op.drop_column('tablets', 'last_seen_at')
    op.drop_column('tablets', 'is_active')
    op.drop_column('tablets', 'location_id')
    op.create_table('admins',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_index('ix_admins_username', 'admins', ['username'], unique=True)
    op.create_table('service_points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='service_points_pkey')
    )
    op.create_index('ix_service_points_id', 'service_points', ['id'], unique=False)
    op.drop_table('user_locations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
